### ISSUE TITLE
NullReferenceException when ShowPopUpNotification action is called

### ISSUE THREAD

**Issue by MiguelIPerez** [Uintra/Uintra#21]
HI Guys,

I am trying to programatically create new members, so, when i hit the "Create" button everythig is fine, excep that when the browser try to render the _Layout_output.cshtml file the line 25 thrown a NullReferenceException.

does anyone face this same error

> Object reference not set to an instance of an object.

stacktrace:

   at Uintra.Notification.Web.NotificationControllerBase.ShowPopupNotifications()
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
   at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerAsyncWrapper.<>c__DisplayClassa.<EndProcessRequest>b__9()
   at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.<>c__DisplayClass4.<Wrap>b__3()
   at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.Wrap[TResult](Func`1 func)
   at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.Wrap(Action action)
   at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerAsyncWrapper.EndProcessRequest(IAsyncResult result)
   at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)

**Comment by MiguelIPerez** [comment]
Yes of course, 

`[HttpPost]
        public ActionResult Register(ModelRegister model)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            if (this.myMemberService.GetByEmail(model.Mail) != null)
            {
                ModelState.AddModelError("","A member with this mail already exist"); ;
                return CurrentUmbracoPage();
            }

            var member = this.myMemberService.CreateMember(model.Mail, model.Mail, model.Name, "member");

            member.SetValue("firstName", model.Name);
            member.SetValue("lastName", model.LastName);
            member.SetValue("relatedUser", model.Name+ " " + model.LastName);
            this.myMemberService.Save(member);
            this.myMemberService.SavePassword(member, model.Password);
            this.myMemberService.AssignRole(member.Id, "WebMaster");

            if (Members.Login(model.Mail, model.Password))
            {
                var currentMember2 = this.myUmbracoHelper.MembershipHelper.GetCurrentMember();
                var loggedMember = Members.GetByUsername(model.Mail);
                if (this.myMemberServiceHelper.IsFirstLoginPerformed(this.myMemberService.GetByKey(loggedMember.GetKey())))
                {
                    SendWelcomeNotification(loggedMember.GetKey());
                }

                this.myMemberServiceHelper.SetFirstLoginPerformed(this.myMemberService.GetByKey(loggedMember.GetKey()));
            }

            var currentMember = this.myUmbracoHelper.MembershipHelper.GetCurrentMember();
            //var currentUser = this.myIntranetUserServices.GetCurrentUserId();
            return Redirect("/");
        }`

**Comment by MiguelIPerez** [comment]
If uncomment the line 
`//var currentUser = this.myIntranetUserServices.GetCurrentUserId();`

Everything start failing or if i comment the previous line also

**Comment by denprodan** [comment]
Hi @MiguelIPerez 
I have couple of questions:
1. Do you try to authenticate memeber after registration?
2. Why you need current member?

**Comment by MiguelIPerez** [comment]
Hi Den.
1.: No, I haven't tried that.
2.: That is just for test purposes

**Comment by denprodan** [comment]
As I can see in your code you login created member
`Members.Login(model.Mail, model.Password)`
But if you want just validate credentials you have to use Membership.Validate
If you want to login creted member please and get it via GetCurrentUser
you need to logout current user and login one more time via 
` FormsAuthentication.SignOut();
  FormsAuthentication.SetAuthCookie(email, true);`

**Comment by UintraContact** [comment]
Hi @MiguelIPerez we consider this task as a closed, since we do not have your input here for more than 14 days, we hope you managed it and it works for you now. else, just reopen / add new issue
