### ISSUE TITLE
Elastic Search Timeout

### ISSUE THREAD

**Issue by ninjaonsafari** [Uintra/Uintra#78]
I'm getting timeout exception when trying to rebuild elastic index:
```
Invalid NEST response built from a unsuccessful low level call on PUT: /uintra_intranet
# Audit trail of this API call:
- [1] BadResponse: Node: http://localhost:9200/ Took: 00:01:00.0278756
- [2] MaxTimeoutReached: Took: -737458.13:30:25.6145681
# OriginalException: System.Net.WebException: Timeout für Vorgang überschritten
at System.Net.HttpWebRequest.GetResponse()
at Elasticsearch.Net.HttpWebRequestConnection.Request[TReturn](RequestData requestData)
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
```

console output when starting elasticsearch:
```
C:\elasticsearch-5.6.16\bin>elasticsearch
[2020-02-04T14:46:55,160][INFO ][o.e.n.Node               ] [] initializing ...
[2020-02-04T14:46:55,348][INFO ][o.e.e.NodeEnvironment    ] [C_oZajE] using [1] data paths, mounts [[(C:)]], net usable_space [74.1gb], net total_space [99.3gb], spins? [unknown], types [NTFS]
[2020-02-04T14:46:55,504][INFO ][o.e.e.NodeEnvironment    ] [C_oZajE] heap size [1.9gb], compressed ordinary object pointers [true]
[2020-02-04T14:46:55,567][INFO ][o.e.n.Node               ] node name [C_oZajE] derived from node ID [C_oZajElSMiddpQxHa7W2Q]; set [node.name] to override
[2020-02-04T14:46:55,567][INFO ][o.e.n.Node               ] version[5.6.16], pid[7592], build[3a740d1/2019-03-13T15:33:36.565Z], OS[Windows Server 2019/10.0/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_241/25.241-b07]
[2020-02-04T14:46:55,567][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Delasticsearch, -Des.path.home=C:\elasticsearch-5.6.16]
[2020-02-04T14:46:56,879][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [aggs-matrix-stats]
[2020-02-04T14:46:56,973][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [ingest-common]
[2020-02-04T14:46:56,973][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [lang-expression]
[2020-02-04T14:46:56,973][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [lang-groovy]
[2020-02-04T14:46:56,973][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [lang-mustache]
[2020-02-04T14:46:56,973][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [lang-painless]
[2020-02-04T14:46:56,973][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [parent-join]
[2020-02-04T14:46:56,973][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [percolator]
[2020-02-04T14:46:56,973][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [reindex]
[2020-02-04T14:46:56,973][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [transport-netty3]
[2020-02-04T14:46:56,988][INFO ][o.e.p.PluginsService     ] [C_oZajE] loaded module [transport-netty4]
[2020-02-04T14:46:56,988][INFO ][o.e.p.PluginsService     ] [C_oZajE] no plugins loaded
[2020-02-04T14:47:00,020][INFO ][o.e.d.DiscoveryModule    ] [C_oZajE] using discovery type [zen]
[2020-02-04T14:47:00,676][INFO ][o.e.n.Node               ] initialized
[2020-02-04T14:47:00,676][INFO ][o.e.n.Node               ] [C_oZajE] starting ...
[2020-02-04T14:47:01,176][INFO ][o.e.t.TransportService   ] [C_oZajE] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2020-02-04T14:47:04,254][INFO ][o.e.c.s.ClusterService   ] [C_oZajE] new_master {C_oZajE}{C_oZajElSMiddpQxHa7W2Q}{5JLQZizpSaW7l7W9QSaH-A}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2020-02-04T14:47:04,457][INFO ][o.e.g.GatewayService     ] [C_oZajE] recovered [2] indices into cluster_state
[2020-02-04T14:47:04,754][INFO ][o.e.c.r.a.AllocationService] [C_oZajE] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[intranet][4], [uintra_intranet][0]] ...]).
[2020-02-04T14:47:04,848][INFO ][o.e.h.n.Netty4HttpServerTransport] [C_oZajE] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2020-02-04T14:47:04,848][INFO ][o.e.n.Node               ] [C_oZajE] started
```

localhost:9300 response:
```
{
  "name" : "C_oZajE",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "kswVrbe3SGKSzHGE1VuQOQ",
  "version" : {
    "number" : "5.6.16",
    "build_hash" : "3a740d1",
    "build_date" : "2019-03-13T15:33:36.565Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```

Versions:
elasticsearch: 5.6.16
java version: "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
umbraco: 7.15.3

I already looked at the issues [19](https://github.com/Uintra/Uintra/issues/19) and [3](https://github.com/Uintra/Uintra/issues/3).

**Comment by denprodan** [comment]
HI @ninjaonsafari. 
Uintra maintain only 5.2.1 ElasticSearch version for now. 
Could you please change it and try one more time?

**Comment by ninjaonsafari** [comment]
Yes it worked with this version. Could you document this stuff and also that ingest-attachment-5.2.1 is needed?
